/**
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.ocelet;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mod Eln</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ocelet.lang.ocelet.OceletPackage#getModEln()
 * @model
 * @generated
 */
public interface ModEln extends EObject
{
} // ModEln
