/**
 * generated by Xtext 2.12.0
 */
package fr.ocelet.lang.ocelet;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paraopt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ocelet.lang.ocelet.Paraopt#getParopt <em>Paropt</em>}</li>
 * </ul>
 *
 * @see fr.ocelet.lang.ocelet.OceletPackage#getParaopt()
 * @model
 * @generated
 */
public interface Paraopt extends Parampart
{
  /**
   * Returns the value of the '<em><b>Paropt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paropt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paropt</em>' attribute.
   * @see #setParopt(String)
   * @see fr.ocelet.lang.ocelet.OceletPackage#getParaopt_Paropt()
   * @model
   * @generated
   */
  String getParopt();

  /**
   * Sets the value of the '{@link fr.ocelet.lang.ocelet.Paraopt#getParopt <em>Paropt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paropt</em>' attribute.
   * @see #getParopt()
   * @generated
   */
  void setParopt(String value);

} // Paraopt
