/**
 * generated by Xtext 2.10.0
 */
package fr.ocelet.lang.ocelet;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paramunit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ocelet.lang.ocelet.Paramunit#getParunit <em>Parunit</em>}</li>
 * </ul>
 *
 * @see fr.ocelet.lang.ocelet.OceletPackage#getParamunit()
 * @model
 * @generated
 */
public interface Paramunit extends Parampart
{
  /**
   * Returns the value of the '<em><b>Parunit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parunit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parunit</em>' attribute.
   * @see #setParunit(String)
   * @see fr.ocelet.lang.ocelet.OceletPackage#getParamunit_Parunit()
   * @model
   * @generated
   */
  String getParunit();

  /**
   * Sets the value of the '{@link fr.ocelet.lang.ocelet.Paramunit#getParunit <em>Parunit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parunit</em>' attribute.
   * @see #getParunit()
   * @generated
   */
  void setParunit(String value);

} // Paramunit
