/**
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.ocelet;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paramdefa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ocelet.lang.ocelet.Paramdefa#getPardefa <em>Pardefa</em>}</li>
 * </ul>
 *
 * @see fr.ocelet.lang.ocelet.OceletPackage#getParamdefa()
 * @model
 * @generated
 */
public interface Paramdefa extends Parampart
{
  /**
   * Returns the value of the '<em><b>Pardefa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pardefa</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pardefa</em>' attribute.
   * @see #setPardefa(String)
   * @see fr.ocelet.lang.ocelet.OceletPackage#getParamdefa_Pardefa()
   * @model
   * @generated
   */
  String getPardefa();

  /**
   * Sets the value of the '{@link fr.ocelet.lang.ocelet.Paramdefa#getPardefa <em>Pardefa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pardefa</em>' attribute.
   * @see #getPardefa()
   * @generated
   */
  void setPardefa(String value);

} // Paramdefa
