/**
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.ocelet;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rangevals</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ocelet.lang.ocelet.Rangevals#getParmin <em>Parmin</em>}</li>
 *   <li>{@link fr.ocelet.lang.ocelet.Rangevals#getParmax <em>Parmax</em>}</li>
 * </ul>
 *
 * @see fr.ocelet.lang.ocelet.OceletPackage#getRangevals()
 * @model
 * @generated
 */
public interface Rangevals extends Parampart
{
  /**
   * Returns the value of the '<em><b>Parmin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parmin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parmin</em>' attribute.
   * @see #setParmin(String)
   * @see fr.ocelet.lang.ocelet.OceletPackage#getRangevals_Parmin()
   * @model
   * @generated
   */
  String getParmin();

  /**
   * Sets the value of the '{@link fr.ocelet.lang.ocelet.Rangevals#getParmin <em>Parmin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parmin</em>' attribute.
   * @see #getParmin()
   * @generated
   */
  void setParmin(String value);

  /**
   * Returns the value of the '<em><b>Parmax</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parmax</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parmax</em>' attribute.
   * @see #setParmax(String)
   * @see fr.ocelet.lang.ocelet.OceletPackage#getRangevals_Parmax()
   * @model
   * @generated
   */
  String getParmax();

  /**
   * Sets the value of the '{@link fr.ocelet.lang.ocelet.Rangevals#getParmax <em>Parmax</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parmax</em>' attribute.
   * @see #getParmax()
   * @generated
   */
  void setParmax(String value);

} // Rangevals
