/**
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.ocelet;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struc Var Def</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ocelet.lang.ocelet.OceletPackage#getStrucVarDef()
 * @model
 * @generated
 */
public interface StrucVarDef extends StrucEln
{
} // StrucVarDef
