/*
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractOceletScopeProvider extends XbaseBatchScopeProvider {
}
