/**
 * generated by Xtext
 */
package fr.ocelet.lang.validation;

import fr.ocelet.lang.validation.AbstractOceletValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class OceletValidator extends AbstractOceletValidator {
}
