/**
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.ui.contentassist;

import fr.ocelet.lang.ui.contentassist.AbstractOceletProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OceletProposalProvider extends AbstractOceletProposalProvider {
}
