/**
 * generated by Xtext
 */
package fr.ocelet.lang.ui.contentassist;

import fr.ocelet.lang.ui.contentassist.AbstractOceletProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class OceletProposalProvider extends AbstractOceletProposalProvider {
}
