/*
 * generated by Xtext
 */
package fr.ocelet.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.ocelet.lang.services.OceletGrammarAccess;

public class OceletParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OceletGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.ocelet.lang.parser.antlr.internal.InternalOceletParser createParser(XtextTokenStream stream) {
		return new fr.ocelet.lang.parser.antlr.internal.InternalOceletParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public OceletGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OceletGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
