/*
 * generated by Xtext 2.12.0
 */
package fr.ocelet.lang.parser.antlr;

import com.google.inject.Inject;
import fr.ocelet.lang.parser.antlr.internal.InternalOceletParser;
import fr.ocelet.lang.services.OceletGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OceletParser extends AbstractAntlrParser {

	@Inject
	private OceletGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOceletParser createParser(XtextTokenStream stream) {
		return new InternalOceletParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public OceletGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OceletGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
