/*
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OceletAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/ocelet/lang/parser/antlr/internal/InternalOcelet.tokens");
	}
}
