/*
 * generated by Xtext
 */
package fr.ocelet.lang.validation

import fr.ocelet.lang.ocelet.OceletPackage
import fr.ocelet.lang.ocelet.Paramdefa
import fr.ocelet.lang.ocelet.Parameter
import fr.ocelet.lang.ocelet.Rangevals
import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class OceletValidator extends AbstractOceletValidator {

// TODO : Vérifier que default est d'un type compatible avec le type déclaré du parametre

	@Check
	def checkParamDefaultWithinRange(Parameter parameter) {
		if (parameter.paramparts != null) {
			var sdef = ""
			var rgmin = 0.0
			var rgmax = 0.0
			var rangeDef = false
			for (pp : parameter.paramparts) {
				switch (pp) {
					Paramdefa: {
						sdef = pp.pardefa
					}
					Rangevals: {
						try {
						  rgmin = new Double(pp.parmin)
						  rgmax = new Double(pp.parmax)
						  rangeDef = true
						} catch (NumberFormatException nfe) {
							warning('Parameter range values must be valid numeric values',OceletPackage.Literals.PARAMETER__NAME)
						}
					}
				}
			}
			if (rangeDef) {
				try {
					val ddef = new Double(sdef)
					if ((ddef < rgmin) || (ddef > rgmax))
						warning('The default value of parameter ' + parameter.name + ' is not within the defined range',
							OceletPackage.Literals.PARAMETER__NAME)
				} catch (NumberFormatException e) {
					warning(
						'The parameter Range can only be used for numeric values and ' + sdef +
							' is not a valid numeric value.', OceletPackage.Literals.PARAMETER__NAME)
				}

			}
		}
	}
}
