/*
* generated by Xtext
*/
package fr.ocelet.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class OceletStandaloneSetup extends OceletStandaloneSetupGenerated{

	public static void doSetup() {
		new OceletStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

