/*
 * generated by Xtext
 */
package fr.ocelet.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OceletUiModule extends fr.ocelet.lang.ui.AbstractOceletUiModule {
	public OceletUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
