/*
 * generated by Xtext
 * And adapted by Pascal Degenne
 */
package fr.ocelet.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.resource.containers.IAllContainersState;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.Singleton;

import fr.ocelet.lang.OcltOutputConfigurationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OceletUiModule extends fr.ocelet.lang.ui.AbstractOceletUiModule {
	public OceletUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configure(Binder binder) {
		super.configure(binder);

		binder.bind(IOutputConfigurationProvider.class)
				.to(OcltOutputConfigurationProvider.class).in(Singleton.class);
	}
	
}
