/**
 * generated by Xtext
 */
package fr.ocelet.lang.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class OceletQuickfixProvider extends XbaseQuickfixProvider {
}
