/**
 * generated by Xtext 2.9.1
 */
package fr.ocelet.lang.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class OceletQuickfixProvider extends XbaseQuickfixProvider {
}
